services:
  - type: web
    name: undercovered
    env: node
    plan: free
    buildCommand: npm install && cd client && npm install --legacy-peer-deps && CI=false GENERATE_SOURCEMAP=false npm run build
    startCommand: node server-simple.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: MAX_FILE_SIZE
        value: 52428800
      - key: ALLOWED_FILE_TYPES
        value: image/jpeg,image/png,image/gif,video/mp4,video/webm,application/pdf
      - key: CLIENT_URL
        value: https://undercovered.onrender.com
